### ISSUE TITLE
Set up prettier and eslint

### ISSUE THREAD

**Issue by natalieacevedo** [haplo/clarita-frontend#10]

**Comment by natalieacevedo** [comment]
Finished, please let me know if you have any setup preference you will like to add.

**Comment by haplo** [comment]
Please set up prettier to 90 characters per line.

After prettier is set up reformat the whole codebase, with something like `yarn prettier --write \"src/**/*.{js,jsx}\"`, and create a single commit that has **only these changes**.

Then add a [.git-blame-ignored-revs](https://github.com/prettier/prettier/blob/main/.git-blame-ignore-revs) file with the commit hash of the reformatted files. This way we can ignore the pure formatting changes when doing git blame.

**Comment by natalieacevedo** [comment]
ok, I did it, gonna push it now, we should do another commit with the typescript changes
